# Generated by Django 2.2.24 on 2021-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month',
            field=models.CharField(default='', max_length=128, verbose_name='месяц'),
            preserve_default=False,
        ),
    ]
